defaults:
  - paths
  - model: L32-1 # L32-1, D2-16-A2, P-1
  - generation: original_prompts # original_prompts
  - time_series: expert_output # attention_outputs, expert_output
  - phyid: discrete  # discrete
  - deactivation_analysis: base 

